title: WikinMongo
description: Simple node.js script to import Wikipedia XML dump into MongoDB database.
google_analytics: UA-9582613-4
show_downloads: true
theme: jekyll-theme-leap-day

gems:
  - jekyll-mentions
